import '../styles/global.css';
import { SideBar } from './components';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="app">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
